#!/bin/bash
a=$1
b=$2
c=$3
d=$4
result=""
for(( i=0; i<a; i++ ))
do
   result+="$d"
   for(( j=1; j<b-1; j++ ))
   do
      if ((c == 1 )) || (( i == 0 )) || (( i == a-1 )); then
         result+="$d"
      else
         result+=" "
      fi
   done
   result+="$d\n"
done
printf "$result"
